### ISSUE TITLE
DM FQE?

### ISSUE THREAD

**Issue by jonathanhuml** [clvoloshin/COBS#15]
Hello Cameron! I am attempting to replicate the DM FQE (or what I think is the pure direct, model-free FQE method) results from the paper. I see in the "estimate" functions I can find in the repo, after obtaining the Q-values, that dr, mag, am, sdr and imp_samp all have "evaluate" functions nested inside this "estimate" function. However, I'm having a tough time locating an "evaluate" function implemented in the DM class to get a corresponding value estimate to compare to the "true" value. 

Intuition here is to take the last set of Q values at horizon=T for Nth traj--> dot product with eval policy --> avg across all N. Take the squared difference of this estimate with the true estimate. Does this sound comparable to what you all did for the benchmark paper?

**Comment by clvoloshin** [comment]
AM = Average Model/Method is the direct estimate. It is referred to as DM in the paper and the code has a poor name for it and should be changed at this point to avoid confusion. So, inside the evaluate function you have all of the hybrid methods as you mentioned + AM (DM) which is the estimate you're looking for.

The DM estimate is the average (hence why I initially called it Average Method) over the first Q value because you want to find the average of how the policy will perform starting from the initial state. See the intro to section E.3.2 of the appendix of the paper (https://arxiv.org/pdf/1911.06854.pdf).

**Comment by jonathanhuml** [comment]
Thanks a ton--this was very helpful

**Comment by clvoloshin** [comment]
Sure, let me know if you have other questions! Thanks for your interest in the repo
